/*****************************************************************************/
/*  ERRNO.H  v1.10#                                                          */
/*  Copyright (c) 1995-1997 Texas Instruments Incorporated                   */
/*****************************************************************************/

#ifndef _ERRNO
#define _ERRNO

extern int errno;

#define EDOM   1
#define ERANGE 2
#define ENOENT 3
#define EFPOS  5

#endif
